import { Board } from "../../games/amazons/board";
// import { NextPage } from "next";
// import { Head } from "next/document";
import { Client } from "boardgame.io/react";
import { AmazonsGame } from "../../games/amazons/game";

const App = Client({
  game: AmazonsGame,
  board: Board,
});
export default App;
/* const AmazonsPage: NextPage = () => {
  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
        <Board G={{fen: DEFAULT_POSITIONS[6]}}/>
    </>
  );
};
export default AmazonsPage; */
